import { defineConfig } from "tsup"

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/access/index.ts",
    "src/ability/index.ts",
    "src/ability/react.tsx",
    "src/server/index.ts",
    "src/server/nest/index.ts",
    "src/client/web.ts",
    "src/client/native.ts",
  ],
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  splitting: true,
  sourcemap: true,
  external: [
    "better-auth",
    "@better-auth/api-key",
    "@better-auth/expo",
    "@better-auth/redis-storage",
    "@casl/ability",
    "@casl/react",
    "@thallesp/nestjs-better-auth",
    "nest-casl",
    "@nestjs/common",
    "@nestjs/core",
    "react",
    "react-native",
    "mongodb",
    "mongoose",
    "@workspace/redis",
    "@workspace/config",
  ],
})
